version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws --version
  build:
    commands:
      - echo "Build started"
      - echo "Test build phase"
  post_build:
    commands:
      - echo "Build completed" 