version: 0.2

# ==========================================
# DATABASE MIGRATION BUILD SPECIFICATION
# ==========================================
# This buildspec is used by CodeBuild to run database migrations
# It runs within the VPC and has access to the private RDS instance

env:
  variables:
    NODE_ENV: "production"
    MIGRATION_MODE: "true"
  parameter-store:
    DATABASE_URL: "/pathfinder/database/connection-string"
    DATABASE_PASSWORD: "/pathfinder/database/password"
  
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies for database migrations..."
      - cd apps/web
      - npm ci --production=false

  pre_build:
    commands:
      - echo "Retrieving database credentials from Secrets Manager..."
      - |
        DB_SECRET=$(aws secretsmanager get-secret-value --secret-id $DATABASE_SECRET_ARN --query SecretString --output text)
        export DATABASE_URL=$(echo $DB_SECRET | jq -r '.database_url')
      - echo "Database connection configured for migrations"

  build:
    commands:
      - echo "Running database migrations..."
      - npm run db:migrate
      - echo "Database migrations completed successfully"

  post_build:
    commands:
      - echo "Migration build completed at $(date)"

cache:
  paths:
    - 'apps/web/node_modules/**/*'
    - 'apps/web/.next/cache/**/*'

# No artifacts needed for migration builds
artifacts:
  files:
    - migration-log.txt
  name: migration-artifacts

# Build reports for migration status
reports:
  migration-report:
    files:
      - 'migration-report.xml'
    file-format: 'JUNITXML' 